2024-10-07 01:40:58,104 | WARNING | Неверный тип данных для объекта Runner
Traceback (most recent call last):
  File "D:\PytonProjects\UrbanUn\TrainingProj\PythonEduProject\Module12\tests\tests_12_4.py", line 26, in test_run
    r2 = Runner(2)
         ^^^^^^^^^
  File "D:\PytonProjects\UrbanUn\TrainingProj\PythonEduProject\Module12\rt_with_exceptions.py", line 6, in __init__
    raise TypeError(f'Имя может быть только строкой, передано {type(name).__name__}')
TypeError: Имя может быть только строкой, передано int
2024-10-07 01:40:58,110 | WARNING | Неверная скорость для объекта Runner
Traceback (most recent call last):
  File "D:\PytonProjects\UrbanUn\TrainingProj\PythonEduProject\Module12\tests\tests_12_4.py", line 15, in test_walk
    r1 = Runner('Tom', -5)
         ^^^^^^^^^^^^^^^^^
  File "D:\PytonProjects\UrbanUn\TrainingProj\PythonEduProject\Module12\rt_with_exceptions.py", line 11, in __init__
    raise ValueError(f'Скорость не может быть отрицательной, сейчас {speed}')
ValueError: Скорость не может быть отрицательной, сейчас -5
